- name: Azure AD 角色文件
  href: index.yml
- name: 概觀
  items:
    - name: 什麼是 Azure AD RBAC？
      href: custom-overview.md
    - name: 了解 Azure AD 角色
      href: concept-understand-roles.md
- name: 快速入門
  items:
    - name: 建立無限制的應用程式註冊
      href: quickstart-app-registration-limits.md
- name: 教學課程
  expanded: true
  items:
    - name: 將使用者指派為管理員角色
      href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: 概念
  expanded: true
  items:
    - name: 委派 Azure AD 管理員角色
      href: concept-delegation.md
    - name: 比較預設使用者權限
      href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: 比較 Azure 和 Azure AD 角色
      href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: 了解 Azure AD 中的管理單位
      href: administrative-units.md
- name: 操作指南
  expanded: true
  items:
    - name: 角色和權限
      expanded: true
      items:
        - name: 角色和權限
          href: permissions-reference.md
        - name: 檢視和指派角色
          href: manage-roles-portal.md
        - name: 我的員工委派
          href: my-staff-configure.md
    - name: 自訂角色
      expanded: true
      items:
        - name: 建立自訂角色
          href: custom-create.md
        - name: 檢視自訂角色指派
          href: custom-view-assignments.md
        - name: 在 Azure 入口網站中指派自訂角色
          href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: 在 PowerShell 中指派自訂角色
          href: custom-assign-powershell.md
        - name: 指派企業應用程式的自訂角色
          href: custom-enterprise-apps.md
        - name: 自訂角色權限
          items:
            - name: 應用程式註冊權限
              href: custom-available-permissions.md
            - name: 企業應用程式權限
              href: custom-enterprise-app-permissions.md
            - name: 應用程式同意權限
              href: custom-consent-permissions.md
        - name: 委派應用程式系統管理角色
          href: delegate-app-roles.md
    - name: 將角色指派給群組
      items:
        - name: 群組型角色指派預覽
          href: groups-concept.md
        - name: 建立可指派角色的群組
          href: groups-create-eligible.md
        - name: 將角色指派給群組
          href: groups-assign-role.md
        - name: 從群組移除角色指派
          href: groups-remove-assignment.md
        - name: 檢視群組的角色指派
          href: groups-view-assignments.md
        - name: 讓群組符合 PIM 中角色的資格
          href: groups-pim-eligible.md
        - name: 常見問題集和疑難排解
          href: groups-faq-troubleshooting.md
    - name: 保護您的角色
      items:
        - name: 角色安全性規劃
          href: security-planning.md
        - name: 建立緊急帳戶
          href: security-emergency-access.md
    - name: 管理單位
      items:
        - name: 系統管理單位概觀
          href: administrative-units.md
        - name: 新增和管理
          href: admin-units-manage.md
        - name: 新增和管理使用者
          href: admin-units-add-manage-users.md
        - name: 新增與管理群組
          href: admin-units-add-manage-groups.md
        - name: 指派具有範圍的角色
          href: admin-units-assign-roles.md
        - name: 常見問題集和疑難排解
          href: admin-units-faq-troubleshoot.md
    - name: 疑難排解
      items:
        - name: 取得 Azure AD 支援
          href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: 參考
  items:
    - name: 依工作區分的最低特殊權限角色
      href: delegate-by-task.md
    - name: Microsoft 365 角色文件
      href: m365-workload-docs.md
    - name: 圖形 API
      href: /graph/api/resources/directoryrole?view=graph-rest-1.0
    - name: Azure AD CLI
      href: /cli/azure/ad
    - name: Azure AD PowerShell for Graph
      href: /powershell/azure/active-directory/install-adv2?view=azureadps-2.0
    - name: Azure AD 服務限制
      href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context